### ISSUE TITLE
Pull non-latest tag

### ISSUE THREAD

**Issue by jdahm** [eth-cscs/sarus#11]
Can sarus pull tags other than `latest`? From the help string it seems that it cannot. What is the recommended process to do so on Piz Daint?

@SpiderMonkey1975

**Comment by Madeeks** [comment]
Hello @jdahm, Sarus can indeed pull images using any tag, not just `latest`. The CLI for doing do is the same as with Docker: the image name should be followed by a colon and then the tag, i.e. `ubuntu:18.04`. This is also shown in the [Sarus User guide](https://sarus.readthedocs.io/en/stable/user/user_guide.html#pull-the-docker-image-from-docker-hub).

As far as Sarus goes, the procedure to pull images with a specific tag on Piz Daint is no different than on any other system.

**Comment by jdahm** [comment]
Hi @Madeeks - Thanks for letting me know. My colleague and I were having difficulty pulling a specific image, but the issue must have been elsewhere. I'll try again next time I'm logged into daint.
