### ISSUE TITLE
Runtime Flag to change working directory

### ISSUE THREAD

**Issue by marcodelapierre** [eth-cscs/sarus#2]
This way, when using 3rd party container images, it is still possible to customise the container working directory at runtime.
Might have a syntax similar to Docker: `--workdir / -w`

**Comment by Madeeks** [comment]
Hello @marcodelapierre, this feature was introduced with version 1.1.0, and is controlled through the `--workdir` option of `sarus run`: https://sarus.readthedocs.io/en/1.1.0/user/user_guide.html#working-directory

Please have a look and let us know if it satisfies your request!

**Comment by marcodelapierre** [comment]
Hi @Madeeks , thanks for this!
As a minor feedback, I think it would be good to have the shortcut flag made available as well, `-w` (again, similar to Docker)

**Comment by marcodelapierre** [comment]
Hi @Madeeks , thanks for this!
I am having an issue when using the flag, I am going to open a separate issue.
